# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf

background_opacity 0.85
dynamic_background_opacity yes
window_padding_width 12
cursor_shape beam
cursor_beam_thickness 1.8
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_border_color #7aa2f7
inactive_border_color #292e42

disable_ligatures never
font_family 0xProto Nerd Font Bold
font_size 12
# END_KITTY_THEME
